//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VBGrammar.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="VBGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IVBGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.startRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStartRule([NotNull] VBGrammarParser.StartRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule([NotNull] VBGrammarParser.ModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.moduleHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleHeader([NotNull] VBGrammarParser.ModuleHeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.moduleConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleConfig([NotNull] VBGrammarParser.ModuleConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.moduleConfigElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleConfigElement([NotNull] VBGrammarParser.ModuleConfigElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.moduleAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleAttributes([NotNull] VBGrammarParser.ModuleAttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.moduleDeclarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclarations([NotNull] VBGrammarParser.ModuleDeclarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>optionBaseStmt</c>
	/// labeled alternative in <see cref="VBGrammarParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionBaseStmt([NotNull] VBGrammarParser.OptionBaseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>optionCompareStmt</c>
	/// labeled alternative in <see cref="VBGrammarParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionCompareStmt([NotNull] VBGrammarParser.OptionCompareStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>optionExplicitStmt</c>
	/// labeled alternative in <see cref="VBGrammarParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionExplicitStmt([NotNull] VBGrammarParser.OptionExplicitStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>optionPrivateModuleStmt</c>
	/// labeled alternative in <see cref="VBGrammarParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionPrivateModuleStmt([NotNull] VBGrammarParser.OptionPrivateModuleStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.moduleDeclarationsElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclarationsElement([NotNull] VBGrammarParser.ModuleDeclarationsElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.moduleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleBody([NotNull] VBGrammarParser.ModuleBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.moduleBodyElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleBodyElement([NotNull] VBGrammarParser.ModuleBodyElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.moduleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleBlock([NotNull] VBGrammarParser.ModuleBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.attributeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeStmt([NotNull] VBGrammarParser.AttributeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] VBGrammarParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.blockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStmt([NotNull] VBGrammarParser.BlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.appactivateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppactivateStmt([NotNull] VBGrammarParser.AppactivateStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.beepStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBeepStmt([NotNull] VBGrammarParser.BeepStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.chdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChdirStmt([NotNull] VBGrammarParser.ChdirStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.chdriveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChdriveStmt([NotNull] VBGrammarParser.ChdriveStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.closeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCloseStmt([NotNull] VBGrammarParser.CloseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.constStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstStmt([NotNull] VBGrammarParser.ConstStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.constSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstSubStmt([NotNull] VBGrammarParser.ConstSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.dateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateStmt([NotNull] VBGrammarParser.DateStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.declareStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareStmt([NotNull] VBGrammarParser.DeclareStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.deftypeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeftypeStmt([NotNull] VBGrammarParser.DeftypeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.deleteSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteSettingStmt([NotNull] VBGrammarParser.DeleteSettingStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.doLoopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoLoopStmt([NotNull] VBGrammarParser.DoLoopStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.endStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndStmt([NotNull] VBGrammarParser.EndStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.enumerationStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationStmt([NotNull] VBGrammarParser.EnumerationStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.enumerationStmt_Constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationStmt_Constant([NotNull] VBGrammarParser.EnumerationStmt_ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.eraseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEraseStmt([NotNull] VBGrammarParser.EraseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.errorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitErrorStmt([NotNull] VBGrammarParser.ErrorStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.eventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventStmt([NotNull] VBGrammarParser.EventStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.exitStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExitStmt([NotNull] VBGrammarParser.ExitStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.filecopyStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilecopyStmt([NotNull] VBGrammarParser.FilecopyStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.forEachStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachStmt([NotNull] VBGrammarParser.ForEachStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.forNextStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForNextStmt([NotNull] VBGrammarParser.ForNextStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.functionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionStmt([NotNull] VBGrammarParser.FunctionStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.getStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetStmt([NotNull] VBGrammarParser.GetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.goSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoSubStmt([NotNull] VBGrammarParser.GoSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.goToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoToStmt([NotNull] VBGrammarParser.GoToStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>inlineIfThenElse</c>
	/// labeled alternative in <see cref="VBGrammarParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineIfThenElse([NotNull] VBGrammarParser.InlineIfThenElseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>blockIfThenElse</c>
	/// labeled alternative in <see cref="VBGrammarParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockIfThenElse([NotNull] VBGrammarParser.BlockIfThenElseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.ifBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfBlockStmt([NotNull] VBGrammarParser.IfBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.ifConditionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfConditionStmt([NotNull] VBGrammarParser.IfConditionStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.ifElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfElseIfBlockStmt([NotNull] VBGrammarParser.IfElseIfBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.ifElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfElseBlockStmt([NotNull] VBGrammarParser.IfElseBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.implementsStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplementsStmt([NotNull] VBGrammarParser.ImplementsStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.inputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputStmt([NotNull] VBGrammarParser.InputStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.killStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKillStmt([NotNull] VBGrammarParser.KillStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetStmt([NotNull] VBGrammarParser.LetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.lineInputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineInputStmt([NotNull] VBGrammarParser.LineInputStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.loadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoadStmt([NotNull] VBGrammarParser.LoadStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.lockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLockStmt([NotNull] VBGrammarParser.LockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.lsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLsetStmt([NotNull] VBGrammarParser.LsetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.macroConstStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroConstStmt([NotNull] VBGrammarParser.MacroConstStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.macroIfThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroIfThenElseStmt([NotNull] VBGrammarParser.MacroIfThenElseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.macroIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroIfBlockStmt([NotNull] VBGrammarParser.MacroIfBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.macroElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroElseIfBlockStmt([NotNull] VBGrammarParser.MacroElseIfBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.macroElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroElseBlockStmt([NotNull] VBGrammarParser.MacroElseBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.midStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMidStmt([NotNull] VBGrammarParser.MidStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.mkdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMkdirStmt([NotNull] VBGrammarParser.MkdirStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.nameStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameStmt([NotNull] VBGrammarParser.NameStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.onErrorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnErrorStmt([NotNull] VBGrammarParser.OnErrorStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.onGoToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnGoToStmt([NotNull] VBGrammarParser.OnGoToStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.onGoSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnGoSubStmt([NotNull] VBGrammarParser.OnGoSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.openStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpenStmt([NotNull] VBGrammarParser.OpenStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.outputList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputList([NotNull] VBGrammarParser.OutputListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.outputList_Expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputList_Expression([NotNull] VBGrammarParser.OutputList_ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.printStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStmt([NotNull] VBGrammarParser.PrintStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.propertyGetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyGetStmt([NotNull] VBGrammarParser.PropertyGetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.propertySetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertySetStmt([NotNull] VBGrammarParser.PropertySetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.propertyLetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyLetStmt([NotNull] VBGrammarParser.PropertyLetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.putStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPutStmt([NotNull] VBGrammarParser.PutStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.raiseEventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaiseEventStmt([NotNull] VBGrammarParser.RaiseEventStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.randomizeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRandomizeStmt([NotNull] VBGrammarParser.RandomizeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.redimStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRedimStmt([NotNull] VBGrammarParser.RedimStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.redimSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRedimSubStmt([NotNull] VBGrammarParser.RedimSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.resetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResetStmt([NotNull] VBGrammarParser.ResetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.resumeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResumeStmt([NotNull] VBGrammarParser.ResumeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmt([NotNull] VBGrammarParser.ReturnStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.rmdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRmdirStmt([NotNull] VBGrammarParser.RmdirStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.rsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRsetStmt([NotNull] VBGrammarParser.RsetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.savepictureStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSavepictureStmt([NotNull] VBGrammarParser.SavepictureStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.saveSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSaveSettingStmt([NotNull] VBGrammarParser.SaveSettingStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.seekStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeekStmt([NotNull] VBGrammarParser.SeekStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.selectCaseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectCaseStmt([NotNull] VBGrammarParser.SelectCaseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondIs</c>
	/// labeled alternative in <see cref="VBGrammarParser.sC_Selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondIs([NotNull] VBGrammarParser.CaseCondIsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondTo</c>
	/// labeled alternative in <see cref="VBGrammarParser.sC_Selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondTo([NotNull] VBGrammarParser.CaseCondToContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondValue</c>
	/// labeled alternative in <see cref="VBGrammarParser.sC_Selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondValue([NotNull] VBGrammarParser.CaseCondValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.sC_Case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSC_Case([NotNull] VBGrammarParser.SC_CaseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondElse</c>
	/// labeled alternative in <see cref="VBGrammarParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondElse([NotNull] VBGrammarParser.CaseCondElseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondSelection</c>
	/// labeled alternative in <see cref="VBGrammarParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondSelection([NotNull] VBGrammarParser.CaseCondSelectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.sendkeysStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSendkeysStmt([NotNull] VBGrammarParser.SendkeysStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.setattrStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetattrStmt([NotNull] VBGrammarParser.SetattrStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.setStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetStmt([NotNull] VBGrammarParser.SetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.stopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStopStmt([NotNull] VBGrammarParser.StopStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.subStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubStmt([NotNull] VBGrammarParser.SubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.timeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeStmt([NotNull] VBGrammarParser.TimeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.typeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeStmt([NotNull] VBGrammarParser.TypeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.typeStmt_Element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeStmt_Element([NotNull] VBGrammarParser.TypeStmt_ElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.typeOfStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeOfStmt([NotNull] VBGrammarParser.TypeOfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.unloadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnloadStmt([NotNull] VBGrammarParser.UnloadStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.unlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnlockStmt([NotNull] VBGrammarParser.UnlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsStruct</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsStruct([NotNull] VBGrammarParser.VsStructContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAdd</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAdd([NotNull] VBGrammarParser.VsAddContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsLt</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsLt([NotNull] VBGrammarParser.VsLtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAddressOf</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAddressOf([NotNull] VBGrammarParser.VsAddressOfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsNew</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsNew([NotNull] VBGrammarParser.VsNewContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsMult</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsMult([NotNull] VBGrammarParser.VsMultContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsNegation</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsNegation([NotNull] VBGrammarParser.VsNegationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAssign</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAssign([NotNull] VBGrammarParser.VsAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsLike</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsLike([NotNull] VBGrammarParser.VsLikeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsDiv</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsDiv([NotNull] VBGrammarParser.VsDivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsPlus</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsPlus([NotNull] VBGrammarParser.VsPlusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsNot</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsNot([NotNull] VBGrammarParser.VsNotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsGeq</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsGeq([NotNull] VBGrammarParser.VsGeqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsTypeOf</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsTypeOf([NotNull] VBGrammarParser.VsTypeOfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsICS</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsICS([NotNull] VBGrammarParser.VsICSContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsNeq</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsNeq([NotNull] VBGrammarParser.VsNeqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsXor</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsXor([NotNull] VBGrammarParser.VsXorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAnd</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAnd([NotNull] VBGrammarParser.VsAndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsLeq</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsLeq([NotNull] VBGrammarParser.VsLeqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsPow</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsPow([NotNull] VBGrammarParser.VsPowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsIs</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsIs([NotNull] VBGrammarParser.VsIsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsMod</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsMod([NotNull] VBGrammarParser.VsModContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAmp</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAmp([NotNull] VBGrammarParser.VsAmpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsOr</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsOr([NotNull] VBGrammarParser.VsOrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsMinus</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsMinus([NotNull] VBGrammarParser.VsMinusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsLiteral</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsLiteral([NotNull] VBGrammarParser.VsLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsEqv</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsEqv([NotNull] VBGrammarParser.VsEqvContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsImp</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsImp([NotNull] VBGrammarParser.VsImpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsGt</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsGt([NotNull] VBGrammarParser.VsGtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsEq</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsEq([NotNull] VBGrammarParser.VsEqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsMid</c>
	/// labeled alternative in <see cref="VBGrammarParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsMid([NotNull] VBGrammarParser.VsMidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.variableStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableStmt([NotNull] VBGrammarParser.VariableStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.variableListStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableListStmt([NotNull] VBGrammarParser.VariableListStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.variableSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableSubStmt([NotNull] VBGrammarParser.VariableSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.whileWendStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileWendStmt([NotNull] VBGrammarParser.WhileWendStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.widthStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWidthStmt([NotNull] VBGrammarParser.WidthStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.withStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWithStmt([NotNull] VBGrammarParser.WithStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.writeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWriteStmt([NotNull] VBGrammarParser.WriteStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.fileNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileNumber([NotNull] VBGrammarParser.FileNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.explicitCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitCallStmt([NotNull] VBGrammarParser.ExplicitCallStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.eCS_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitECS_ProcedureCall([NotNull] VBGrammarParser.ECS_ProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.eCS_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitECS_MemberProcedureCall([NotNull] VBGrammarParser.ECS_MemberProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.implicitCallStmt_InBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplicitCallStmt_InBlock([NotNull] VBGrammarParser.ImplicitCallStmt_InBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.iCS_B_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_B_MemberProcedureCall([NotNull] VBGrammarParser.ICS_B_MemberProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.iCS_B_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_B_ProcedureCall([NotNull] VBGrammarParser.ICS_B_ProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.implicitCallStmt_InStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplicitCallStmt_InStmt([NotNull] VBGrammarParser.ImplicitCallStmt_InStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.iCS_S_VariableOrProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_VariableOrProcedureCall([NotNull] VBGrammarParser.ICS_S_VariableOrProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.iCS_S_ProcedureOrArrayCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_ProcedureOrArrayCall([NotNull] VBGrammarParser.ICS_S_ProcedureOrArrayCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.iCS_S_MembersCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_MembersCall([NotNull] VBGrammarParser.ICS_S_MembersCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.iCS_S_MemberCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_MemberCall([NotNull] VBGrammarParser.ICS_S_MemberCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.iCS_S_DictionaryCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_DictionaryCall([NotNull] VBGrammarParser.ICS_S_DictionaryCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.argsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgsCall([NotNull] VBGrammarParser.ArgsCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.argCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgCall([NotNull] VBGrammarParser.ArgCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.dictionaryCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictionaryCallStmt([NotNull] VBGrammarParser.DictionaryCallStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgList([NotNull] VBGrammarParser.ArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg([NotNull] VBGrammarParser.ArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.argDefaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgDefaultValue([NotNull] VBGrammarParser.ArgDefaultValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.subscripts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscripts([NotNull] VBGrammarParser.SubscriptsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscript([NotNull] VBGrammarParser.SubscriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.ambiguousIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmbiguousIdentifier([NotNull] VBGrammarParser.AmbiguousIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.asTypeClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsTypeClause([NotNull] VBGrammarParser.AsTypeClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseType([NotNull] VBGrammarParser.BaseTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.certainIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCertainIdentifier([NotNull] VBGrammarParser.CertainIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.comparisonOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonOperator([NotNull] VBGrammarParser.ComparisonOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.complexType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexType([NotNull] VBGrammarParser.ComplexTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.fieldLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldLength([NotNull] VBGrammarParser.FieldLengthContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.letterrange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetterrange([NotNull] VBGrammarParser.LetterrangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.lineLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineLabel([NotNull] VBGrammarParser.LineLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] VBGrammarParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] VBGrammarParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.typeHint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeHint([NotNull] VBGrammarParser.TypeHintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVisibility([NotNull] VBGrammarParser.VisibilityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VBGrammarParser.ambiguousKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmbiguousKeyword([NotNull] VBGrammarParser.AmbiguousKeywordContext context);
}
